api_version: v1
name: HSS
spec:
  - applications:
      - vendor_id: VENDOR_ID_3GPP
        app_id: DIAMETER_APPLICATION_Cx
    mode: Server
    watchdog_timeout: 30
    transport_type: TCP
    local:
      ip_address: 10.26.61.69
      hostname: dev-probe-1.epc.mnc840.mcc310.3gppnetwork.org
      realm: epc.mnc840.mcc310.3gppnetwork.org
      port: 3870
    peer:
      ip_address: 199.255.7.206
      hostname: rbx-prd-dra.epc.mnc840.mcc310.3gppnetwork.org
      realm: epc.mnc840.mcc310.3gppnetwork.org
      port: 3870